openapi: 3.0.3
info:
  version: "1.0"
  title: "Department Management"
  contact:
    email: "m.ehab.rabea@gmail.com"
    name: "Mohamed Ehab"

servers:
  - url: http://localhost:7002/

tags:
  - name: Department
  - name: DepartmentLookup

paths:
  /lookup/departments:
    get:
      tags:
        - DepartmentLookup
      summary: Retrieve All Departments (public)
      operationId: getAllDepartmentsLookup
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/schemas/LookupResultSet'
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

  /departments:
    post:
      tags:
        - Department
      summary: Create department
      operationId: createDepartment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepartmentDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/schemas/NewRecordVTO'
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

    get:
      tags:
        - Department
      summary: Retrieve list of Departments
      operationId: getAllDepartments
      parameters:
        - $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/parameters/QPQuickSearch'
        - $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/parameters/QPCreatedOnFrom'
        - $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/parameters/QPCreatedOnTo'
        - $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/parameters/QPLastModifiedOnFrom'
        - $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/parameters/QPLastModifiedOnTo'
        - $ref: '../../../../../lib/sql-db-adapter/_swagger/service/swagger.yaml#/components/parameters/QPPageNum'
        - $ref: '../../../../../lib/sql-db-adapter/_swagger/service/swagger.yaml#/components/parameters/QPPageSize'
        - $ref: '../../../../../lib/sql-db-adapter/_swagger/service/swagger.yaml#/components/parameters/QPOrderDir'
        - $ref: '../../../../../lib/sql-db-adapter/_swagger/service/swagger.yaml#/components/parameters/QPOrderBy'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DepartmentResultSet'
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

  /departments/{departmentId}:

    put:
      tags:
        - Department
      summary: Update Department By Id
      operationId: updateDepartmentById
      parameters:
        - $ref: '#/components/parameters/PPDepartmentId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepartmentDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/schemas/NewRecordVTO'
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

    get:
      tags:
        - Department
      summary: Retrieve department
      operationId: getDepartment
      parameters:
        - $ref: '#/components/parameters/PPDepartmentId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DepartmentVTO'
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'


components:
  parameters:
    PPDepartmentId:
      name: departmentId
      in: path
      required: true
      schema:
        type: integer
        format: int32

  schemas:
    DepartmentDTO:
      type: object
      required:
        - title
      properties:
        title:
          type: string
        description:
          type: string

    DepartmentVTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        title:
          type: string
        description:
          type: string
        isActive:
          type: boolean
        createdOn:
          type: string
          format: date-time
        createdBy:
          $ref: '../../../../../service/service/user/_swagger/service/swagger.yaml#/components/schemas/LightUserVTO'
        lastModifiedOn:
          type: string
          format: date-time
        lastModifiedBy:
          $ref: '../../../../../service/service/user/_swagger/service/swagger.yaml#/components/schemas/LightUserVTO'

    DepartmentResultSet:
      type: object
      properties:
        total:
          type: integer
          format: int32
        items:
          type: array
          items:
            $ref: '#/components/schemas/DepartmentListItem'

    DepartmentListItem:
      type: object
      properties:
        id:
          type: integer
          format: int32
        title:
          type: string
        description:
          type: string
        isActive:
          type: boolean
        createdOn:
          type: string
          format: date-time
        createdBy:
          $ref: '../../../../../service/service/user/_swagger/service/swagger.yaml#/components/schemas/LightUserVTO'
        lastModifiedOn:
          type: string
          format: date-time
        lastModifiedBy:
          $ref: '../../../../../service/service/user/_swagger/service/swagger.yaml#/components/schemas/LightUserVTO'