bs.lib.security.public-paths=/auth/login,/auth/register,/auth/activate,/auth/activate/verify,\
  /auth/resend-activation,/auth/forgot-password,/auth/reset-verify,/swagger-ui.html,/swagger-ui/**,/auth/reset-password,\
  /auth/lookups/roles,/favicon.ico,/actuator/health,/actuator/info
