bs.lib.security.public-paths=/auth/login,/users/**,/v3/**,/swagger-ui.html,/swagger-ui/**,/favicon.ico,\
  /actuator/**,/ws/**,/index.html,/topic/**,/app/**,/static/**,/lookup/employee/attendance/status
