openapi: 3.0.3
info:
  version: "1.0"
  title: "Department Management"
  contact:
    email: "m.ehab.rabea@gmail.com"
    name: "Mohamed Ehab"

servers:
  - url: http://localhost:7002/

tags:
  - name: Department

paths:
  /departments/{departmentId}:
    get:
      tags:
        - Department
      summary: Retrieve department
      operationId: getDepartment
      parameters:
        - $ref: '#/components/parameters/PPDepartmentId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PharmacyCartVTO'
        '400':
          $ref: '../../../common/'

  /pharmacies/{pharmacyId}/carts/{cartId}/clear:
    put:
      tags:
        - Pharmacy Cart
      summary: Clear cart
      operationId: clearPharmacyCart
      parameters:
        - $ref: '../../../../../z-pharma-inv/service/pharmacy/_swagger/service/swagger.yaml#/components/parameters/PPPharmacyId'
        - $ref: '../../../../../service/service/cart/_swagger/service/swagger.yaml#/components/parameters/PPCartId'
      responses:
        '204':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/NoContent'
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

  /pharmacies/{pharmacyId}/carts/items:
    post:
      tags:
        - Pharmacy Cart
      summary: Add item to cart
      operationId: addItemToPharmacyCart
      parameters:
        - $ref: '../../../../../z-pharma-inv/service/pharmacy/_swagger/service/swagger.yaml#/components/parameters/PPPharmacyId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../../../../service/service/cart/_swagger/service/swagger.yaml#/components/schemas/CartItemDTO'
        required: true
      responses:
        '204':
          description: No content
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

    put:
      tags:
        - Pharmacy Cart
      summary: Update item In cart
      operationId: updateItemInPharmacyCart
      parameters:
        - $ref: '../../../../../z-pharma-inv/service/pharmacy/_swagger/service/swagger.yaml#/components/parameters/PPPharmacyId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../../../../service/service/cart/_swagger/service/swagger.yaml#/components/schemas/UpdateCartItemDTO'
      responses:
        '204':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/NoContent'
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

    delete:
      tags:
        - Pharmacy Cart
      summary: Delete item from cart
      operationId: deleteItemFromPharmacyCart
      parameters:
        - $ref: '../../../../../service/service/cart/_swagger/service/swagger.yaml#/components/parameters/PPItemId'
        - $ref: '../../../../../z-pharma-inv/service/pharmacy/_swagger/service/swagger.yaml#/components/parameters/PPPharmacyId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../../../../../service/service/cart/_swagger/service/swagger.yaml#/components/schemas/DeleteCartItemDTO'
      responses:
        '204':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/NoContent'
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

  /pharmacies/{pharmacyId}/carts/delivary/time:
    get:
      tags:
        - Pharmacy Cart
      summary: Retrieve expected delivery time
      operationId: getExpectedDeliveryTime
      parameters:
        - $ref: '../../../../../z-pharma-inv/service/pharmacy/_swagger/service/swagger.yaml#/components/parameters/PPPharmacyId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartDeliveryTimeVTO'
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

  /carts/admin/{cartId}/checkout:
    put:
      tags:
        - Admin Cart
      summary: Admin Checkout cart by id
      operationId: adminCheckoutCart
      parameters:
        - $ref: '../../../../../service/service/cart/_swagger/service/swagger.yaml#/components/parameters/PPCartId'
      responses:
        '200':
          description: Checkout success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartCheckoutVTO'
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

  /carts/admin:
    post:
      tags:
        - Admin Cart
      summary: Create Admin cart
      operationId: createAdminCart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminCartDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/schemas/NewRecordVTO'
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

    get:
      tags:
        - Admin Cart
      summary: Retrieve list of Admin carts
      operationId: getAdminCarts
      parameters:
        - name: cartTitle
          in: query
          required: false
          schema:
            type: string
            minLength: 2
        - $ref: '../../../../../z-pharma-inv/service/pharmacy/_swagger/service/swagger.yaml#/components/parameters/QPPharmacyId'
        - $ref: '../../../../../z-pharma-inv/service/pharmacy/_swagger/service/swagger.yaml#/components/parameters/QPPharmacyOwnerId'
        - $ref: '../../../../../z-pharma-inv/service/pharmacy/_swagger/service/swagger.yaml#/components/parameters/QPAssignedToIds'
        - $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/parameters/QPCreatedOnFrom'
        - $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/parameters/QPCreatedOnTo'
        - $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/parameters/QPLastModifiedOnFrom'
        - $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/parameters/QPLastModifiedOnTo'
        - $ref: '../../../../../lib/sql-db-adapter/_swagger/service/swagger.yaml#/components/parameters/QPPageNum'
        - $ref: '../../../../../lib/sql-db-adapter/_swagger/service/swagger.yaml#/components/parameters/QPPageSize'
        - $ref: '../../../../../lib/sql-db-adapter/_swagger/service/swagger.yaml#/components/parameters/QPOrderDir'
        - $ref: '../../../../../lib/sql-db-adapter/_swagger/service/swagger.yaml#/components/parameters/QPOrderBy'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminCartResultSet'
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

  /carts/admin/{cartId}:
    get:
      tags:
        - Admin Cart
      summary: Retrieve Admin cart Details by id
      operationId: getAdminCartDetailsById
      parameters:
        - $ref: '../../../../../service/service/cart/_swagger/service/swagger.yaml#/components/parameters/PPCartId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminCartDetailsVTO'
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

    delete:
      tags:
        - Admin Cart
      summary: Delete Admin cart by id
      operationId: deleteAdminCartById
      parameters:
        - $ref: '../../../../../service/service/cart/_swagger/service/swagger.yaml#/components/parameters/PPCartId'
      responses:
        '204':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/NoContent'
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

  /carts/admin/{cartId}/items:
    post:
      tags:
        - Admin Cart
      summary: Add item to Admin cart
      operationId: addItemToAdminCart
      parameters:
        - $ref: '../../../../../service/service/cart/_swagger/service/swagger.yaml#/components/parameters/PPCartId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../../../../service/service/cart/_swagger/service/swagger.yaml#/components/schemas/CartItemDTO'
        required: true
      responses:
        '204':
          description: No content
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

    put:
      tags:
        - Admin Cart
      summary: Update item In Admin cart
      operationId: updateItemInAdminCart
      parameters:
        - $ref: '../../../../../service/service/cart/_swagger/service/swagger.yaml#/components/parameters/PPCartId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../../../../service/service/cart/_swagger/service/swagger.yaml#/components/schemas/UpdateCartItemDTO'
      responses:
        '204':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/NoContent'
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

  /carts/admin/{cartId}/items/{itemId}:
    delete:
      tags:
        - Admin Cart
      summary: Delete item from Admin cart
      operationId: deleteItemFromAdminCart
      parameters:
        - $ref: '../../../../../service/service/cart/_swagger/service/swagger.yaml#/components/parameters/PPItemId'
        - $ref: '../../../../../service/service/cart/_swagger/service/swagger.yaml#/components/parameters/PPCartId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../../../../../service/service/cart/_swagger/service/swagger.yaml#/components/schemas/DeleteCartItemDTO'
      responses:
        '204':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/NoContent'
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

components:
  parameters:
    PPDepartmentId:
      name: departmentId
      in: path
      required: true
      schema:
        type: integer
        format: int64

  schemas:
    CartDeliveryTimeVTO:
      type: object
      properties:
        dayLabelEn:
          type: string
        dayLabelAr:
          type: string
        date:
          type: string
        timeFrom:
          type: string
        timeTo:
          type: string

    PharmacyCartVTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        pharmacy:
          $ref: '../../../../../z-pharma-inv/service/pharmacy/_swagger/service/swagger.yaml#/components/schemas/PharmacyVTO'
        title:
          type: string
        items:
          type: array
          items:
            $ref: '../../../../../service/service/cart/_swagger/service/swagger.yaml#/components/schemas/CartItemVTO'
        totalItems:
          type: integer
          format: int64
        totalQuantity:
          type: integer
          format: int64
        totalBusinessPrice:
          type: number
          format: double
        finalBusinessPrice:
          type: number
          format: double
        finalCustomerPrice:
          type: number
          format: double
        createdOn:
          type: string
          format: date-time
        createdBy:
          $ref: '../../../../../lib/user-adapter/_swagger/service/swagger.yaml#/components/schemas/LightUserVTO'
        lastModifiedOn:
          type: string
          format: date-time
        lastModifiedBy:
          $ref: '../../../../../lib/user-adapter/_swagger/service/swagger.yaml#/components/schemas/LightUserVTO'

    AdminCartDTO:
      type: object
      required:
        - pharmacyId
      properties:
        pharmacyId:
          type: integer
          format: int64
        title:
          type: string
          minLength: 1
          maxLength: 150
          description: Optional cart title

    AdminCartResultSet:
      type: object
      properties:
        total:
          type: integer
          format: int64
        items:
          type: array
          items:
            $ref: '#/components/schemas/AdminCartListItem'

    AdminCartListItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
        cartTitle:
          type: string
        pharmacy:
          $ref: '../../../../../z-pharma-inv/service/pharmacy/_swagger/service/swagger.yaml#/components/schemas/LightPharmacyVTO'
        assignedTo:
          $ref: '../../../../../lib/user-adapter/_swagger/service/swagger.yaml#/components/schemas/LightUserVTO'
        totalItems:
          type: integer
          format: int64
        totalQuantity:
          type: integer
          format: int64
        totalPrice:
          type: number
          format: double
        createdOn:
          type: string
          format: date-time
        createdBy:
          $ref: '../../../../../lib/user-adapter/_swagger/service/swagger.yaml#/components/schemas/LightUserVTO'
        lastModifiedOn:
          type: string
          format: date-time
        lastModifiedBy:
          $ref: '../../../../../lib/user-adapter/_swagger/service/swagger.yaml#/components/schemas/LightUserVTO'

    AdminCartDetailsVTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        pharmacy:
          $ref: '../../../../../z-pharma-inv/service/pharmacy/_swagger/service/swagger.yaml#/components/schemas/PharmacyVTO'
        items:
          type: array
          items:
            $ref: '../../../../../service/service/cart/_swagger/service/swagger.yaml#/components/schemas/CartItemVTO'
        totalItems:
          type: integer
          format: int64
        totalQuantity:
          type: integer
          format: int64
        totalBusinessPrice:
          type: number
          format: double
        createdOn:
          type: string
          format: date-time
        createdBy:
          $ref: '../../../../../lib/user-adapter/_swagger/service/swagger.yaml#/components/schemas/LightUserVTO'
        lastModifiedOn:
          type: string
          format: date-time
        lastModifiedBy:
          $ref: '../../../../../lib/user-adapter/_swagger/service/swagger.yaml#/components/schemas/LightUserVTO'

    CartCheckoutVTO:
      type: object
      properties:
        orderId:
          type: integer
          format: int64
        owner:
          $ref: '../../../../../lib/user-adapter/_swagger/service/swagger.yaml#/components/schemas/LightUserVTO'
        governorate:
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/schemas/LookupVTO'
        city:
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/schemas/LookupVTO'
        region:
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/schemas/LookupVTO'
        deductedAmount:
          type: number
        paymentMethod:
          type: string