openapi: 3.0.3
info:
  version: "1.0"
  title: "Place Management"
  contact:
    email: "m.ehab.rabea@gmail.com"
    name: "Mohamed Ehab"

servers:
  - url: http://localhost:7002/

tags:
  - name: Place
  - name: Lookup

paths:
  /places:
    post:
      tags:
        - Place
      summary: Create place
      operationId: createPlace
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlaceDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/schemas/NewRecordVTO'
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

    get:
      tags:
        - Place
      summary: Retrieve list of Places
      operationId: getAllPlacesByFilter
      parameters:
        - $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/parameters/QPQuickSearch'
        - $ref: '../../../../../lib/sql-db-adapter/_swagger/service/swagger.yaml#/components/parameters/QPPageNum'
        - $ref: '../../../../../lib/sql-db-adapter/_swagger/service/swagger.yaml#/components/parameters/QPPageSize'
        - $ref: '../../../../../lib/sql-db-adapter/_swagger/service/swagger.yaml#/components/parameters/QPOrderDir'
        - $ref: '../../../../../lib/sql-db-adapter/_swagger/service/swagger.yaml#/components/parameters/QPOrderBy'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaceResultSet'
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

  /places/{placeId}:
    put:
      tags:
        - Place
      summary: Update Place By Id
      operationId: updatePlaceById
      parameters:
        - $ref: '#/components/parameters/PPPlaceId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlaceDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/schemas/NewRecordVTO'
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

    get:
      tags:
        - Place
      summary: Retrieve place
      operationId: getPlaceById
      parameters:
        - $ref: '#/components/parameters/PPPlaceId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaceVTO'
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

    delete:
      tags:
        - Place
      summary: Delete place (soft delete)
      operationId: deletePlaceById
      parameters:
        - $ref: '#/components/parameters/PPPlaceId'
      responses:
        '200':
          description: OK
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

  /lookup/places:
    get:
      tags:
        - Lookup
      summary: Retrieve All Places for lookup (public)
      operationId: getAllPlacesLookup
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/schemas/LookupResultSet'
        '400':
          $ref: '../../../../../lib/common/_swagger/service/swagger.yaml#/components/responses/BadRequest'

components:
  parameters:
    PPPlaceId:
      name: placeId
      in: path
      required: true
      schema:
        type: integer
        format: int32

  schemas:
    PlaceDTO:
      type: object
      required:
        - title
      properties:
        title:
          type: string
        rentValue:
          type: integer
          format: int32
        remainedValue:
          type: integer
          format: int32
        address:
          type: string
        phoneNumber:
          type: string

    PlaceVTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        title:
          type: string
        rentValue:
          type: integer
          format: int32
        remainedValue:
          type: integer
          format: int32
        address:
          type: string
        phoneNumber:
          type: string
        createdOn:
          type: string
          format: date-time
        createdBy:
          $ref: '../../../../../service/service/user/_swagger/service/swagger.yaml#/components/schemas/LightUserVTO'
        lastModifiedOn:
          type: string
          format: date-time
        lastModifiedBy:
          $ref: '../../../../../service/service/user/_swagger/service/swagger.yaml#/components/schemas/LightUserVTO'

    PlaceResultSet:
      type: object
      properties:
        total:
          type: integer
          format: int32
        items:
          type: array
          items:
            $ref: '#/components/schemas/PlaceListItem'

    PlaceListItem:
      type: object
      properties:
        id:
          type: integer
          format: int32
        title:
          type: string
        rentValue:
          type: integer
          format: int32
        remainedValue:
          type: integer
          format: int32
        address:
          type: string
        phoneNumber:
          type: string